import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Admin' at '6/3/16 9:32 AM' with Gradle 2.13
 *
 * @author Admin, @date 6/3/16 9:32 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
       // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
