/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Admin' at '6/3/16 9:32 AM' with Gradle 2.13
 *
 * @author Admin, @date 6/3/16 9:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
